development:
  api_key: 263515600329607
  secret_key: 2649d032a1ca0e33122e3614184ad18c
  callback_url: http://0.0.0.0:3000/
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

production:
  api_key: 263515600329607
  secret_key: 2649d032a1ca0e33122e3614184ad18c
  callback_url: http://www.eventsalsa.com
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0